workflows:
  react-native-ios:
    name: iOS Build
    environment:
      vars:
        XCODE_WORKSPACE: "YourProject.xcworkspace"
        XCODE_SCHEME: "YourScheme"
    scripts:
      - name: Build IPA
        script: |
          xcodebuild archive \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archivePath build/YourProject.xcarchive \
          -destination generic/platform=iOS \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="Your_Profile_Name" \
          DEVELOPMENT_TEAM="Your_Team_ID"
          
          xcodebuild -exportArchive \
          -archivePath build/YourProject.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath build
