workflows:
  ju-zi-ios:
    name: JuZi iOS Production
    environment:
      groups:
        - ios_certs # 包含证书的组
      vars:
        APP_ID: com.company.juzi
        XCODE_SCHEME: "JuZi"
        XCODE_WORKSPACE: "ios/JuZi.xcworkspace"
    scripts:
      - name: Set up Ruby
        script: |
          sudo gem install cocoapods

      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update

      - name: Build IPA
        script: |
          cd ios
          xcodebuild clean archive \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -archivePath ../build/JuZi.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGN_STYLE="Manual" \
          PROVISIONING_PROFILE_SPECIFIER="$IOS_PROVISIONING_PROFILE" \
          DEVELOPMENT_TEAM="$IOS_DEVELOPMENT_TEAM" \
          PRODUCT_BUNDLE_IDENTIFIER="$APP_ID"

          xcodebuild -exportArchive \
          -archivePath ../build/JuZi.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath ../build/artifacts
    artifacts:
      - build/artifacts/**/*.ipa
