workflows:
  ios-workflow:
    name: iOS Production Build
    environment:
      groups:
        - ios_certificates
      vars:
        RUBY_VERSION: "3.3.0"
    scripts:
      - name: Install Ruby Dependencies
        script: |
          brew install openssl@1.1 readline libyaml libffi
          
      - name: Setup Ruby
        script: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
          source ~/.bash_profile
          
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          
          # 安装指定版本Ruby
          RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)" \
          rbenv install $RUBY_VERSION
          rbenv global $RUBY_VERSION
          
          # 验证环境
          which ruby
          ruby -v
          gem env

      - name: Install Cocoapods
        script: |
          gem install --user-install cocoapods -v 1.15.2
          export PATH="$HOME/.gem/ruby/${RUBY_VERSION}/bin:$PATH"
          pod --version
