workflows:
  ios-development:
    name: iOS Development Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/JuZi.xcworkspace"  # 确保与生成的文件名一致
        XCODE_SCHEME: "JuZi"
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          # 如果是 Expo 项目，添加预生成命令
          npx expo prebuild --platform ios --non-interactive
          # 修复旧版依赖警告（可选）
          npm update rimraf glob inflight
      - name: Install CocoaPods
        script: |
          cd ios
          bundle install  # 确保 CocoaPods 版本一致
          pod install --repo-update
      - name: Build IPA
        script: |
          xcodebuild clean
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath build/JuZi.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/JuZi.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build
    artifacts:
      - build/**/*.ipa