scripts:
  - name: Install Pods
    script: |
      cd ios
      pod install --repo-update

  - name: Build IPA
    script: |
      cd ios
      xcodebuild archive \
      -workspace "JuZi.xcworkspace" \  # 注意这里的实际名称
      -scheme "JuZi" \                 # Scheme通常与项目名相同
      -archivePath ../build/JuZi.xcarchive \
      -destination generic/platform=iOS \
      CODE_SIGN_STYLE=Manual \
      PROVISIONING_PROFILE_SPECIFIER="JuZi_Profile" \
      DEVELOPMENT_TEAM="ABCD1234"       # 替换为真实Team ID

      xcodebuild -exportArchive \
      -archivePath ../build/JuZi.xcarchive \
      -exportOptionsPlist ExportOptions.plist \
      -exportPath ../build
